version: '3.8'

services:
  real_estate_app:
    build: .
    container_name: real_estate_office_app
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - app-network

networks:
  app-network:
    external: true
