'use client';
import type { PortalDashboard } from '@/lib/portal/workflows';
import { brokerPerformance,kpiPerformance,periodRange } from '@/lib/portal/calculations';
import Chart from './PortalChart';
import Badge,{statusNames} from './StatusBadge';
import WorkflowForm from './WorkflowForm';
export default function BrokerPanel({data,en,executive,save,money}:{data:PortalDashboard;en:boolean;executive:boolean;save:(body:unknown)=>Promise<boolean>;money:(n:number)=>string}){
 const t=(ar:string,english:string)=>en?english:ar,range=periodRange(data.today,'monthly'),monthly=brokerPerformance(data.commissions,range.start,range.end);
 return <div className="space-y-5"><div className="grid sm:grid-cols-3 gap-3"><section className="portal-card">{t('العقود الناجحة هذا الشهر','Closed contracts this month')}<p className="text-3xl font-bold">{monthly.count}</p></section><section className="portal-card">{t('العمولة المكتسبة هذا الشهر','Commission earned this month')}<p className="text-2xl font-bold">{money(monthly.commission)}</p></section><section className="portal-card">{t('الأهداف المسندة','Assigned KPIs')}<p className="text-3xl font-bold">{data.kpis.length}</p></section></div>
 <Chart label={t('اتجاه العمولة لستة أشهر','Six-month commission trend')} rows={Array.from({length:6},(_,i)=>{const d=new Date(`${data.today}T00:00:00Z`);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-5+i);const r=periodRange(d.toISOString().slice(0,10),'monthly');return{label:r.start.slice(0,7),value:brokerPerformance(data.commissions,r.start,r.end).commission};})}/>
 {data.commissions.map(c=><section key={`${c.broker_user_id}:${c.contract_id}`} className="portal-card space-y-3"><h3 className="font-bold">{c.number}</h3><p>{money(c.amount)} · {c.type==='FIXED'?t('مبلغ ثابت','Fixed amount'):`${c.rate}%`} · <Badge en={en} status={c.status}/></p><p>{c.closed_at?`${t('أغلق بتاريخ','Closed on')} ${c.closed_at.slice(0,10)}`:t('لم يؤكد إغلاق العقد بعد','Closing has not been confirmed')}</p>
 {executive&&<WorkflowForm en={en} title={t('تعديل العمولة والصرف','Edit commission & payout')} operation="COMMISSION_SAVE" fixed={{broker_user_id:c.broker_user_id,contract_id:c.contract_id}} save={save} fields={[{name:'type',label:t('نوع العمولة','Type'),value:c.type,options:[{value:'PERCENTAGE',label:t('نسبة','Percentage')},{value:'FIXED',label:t('ثابت','Fixed')}]},{name:'value',label:t('النسبة / المبلغ','Rate / amount'),type:'number',value:c.rate},{name:'basis',label:t('أساس النسبة','Percentage basis'),optional:true,value:c.basis,options:[{value:'DEAL_VALUE',label:t('قيمة العقد','Contract value')},{value:'OFFICE_COMMISSION',label:t('عمولة المكتب','Office commission')}]},{name:'payout_status',label:t('حالة الصرف','Payout status'),value:c.status,options:['pending','approved','paid'].map(value=>({value,label:en?value:statusNames[value]}))},{name:'closed_at',label:t('تاريخ الإغلاق','Closed at'),type:'datetime-local',optional:true,value:c.closed_at?new Date(new Date(c.closed_at).getTime()-new Date(c.closed_at).getTimezoneOffset()*60000).toISOString().slice(0,16):undefined}]}/>}
 </section>)}
 {data.kpis.map(kpi=>{const p=kpiPerformance(kpi,data.commissions,data.today);return<section className="portal-card" key={kpi.id}><h3 className="font-bold">{kpi.name}</h3><p>{kpi.period_start} — {kpi.period_end}</p><p>{t('المحقق','Actual')}: {p.actual} / {t('الهدف','Target')}: {kpi.target} <Badge en={en} status={p.status}/></p><progress className="w-full mt-3 accent-[#2F6D3A]" value={p.actual} max={kpi.target}/></section>;})}
 {!data.commissions.length&&<p className="portal-card">{t('لا توجد عقود مسندة بعد.','No assigned contracts yet.')}</p>}
 </div>;
}
