'use client';
import { useState } from 'react';
import type { PortalDashboard } from '@/lib/portal/workflows';
import WorkflowForm, { Field } from './WorkflowForm';
export default function ExecutiveControls({ data, en, save, money }: { data: PortalDashboard; en: boolean; save: (body: unknown) => Promise<boolean>; money: (n: number) => string }) {
 const [contract,setContract]=useState(''),[payment,setPayment]=useState(''),[due,setDue]=useState(''),[kpi,setKpi]=useState('');
 const t=(ar:string,english:string)=>en?english:ar;
 const f=(name:string,ar:string,english:string,type:Field['type']='text',optional=false,value?:Field['value']):Field=>({name,label:t(ar,english),type,optional,value});
 const options=(name:string,ar:string,english:string,items:{value:string;label:string}[],optional=false,value?:string):Field=>({name,label:t(ar,english),options:items,optional,value});
 const contracts=data.contracts.map(c=>({value:c.id,label:c.number})),brokers=data.customers.filter(c=>c.role==='BROKER').map(c=>({value:c.id,label:c.name}));
 const metrics=[{value:'contract_count',label:t('عدد العقود','Contract count')},{value:'contract_value',label:t('قيمة العقود','Contract value')},{value:'commission',label:t('العمولة','Commission')},{value:'custom',label:t('مؤشر مخصص','Custom')}];
 const periods=[{value:'monthly',label:t('شهري','Monthly')},{value:'quarterly',label:t('ربع سنوي','Quarterly')}];
 const selectedKpi=data.kpis.find(k=>k.id===kpi);
 const kpiFields=(edit=false):Field[]=>[...(edit?[]:[options('broker_user_id','الوسيط','Broker',brokers)]),f('name','اسم الهدف','KPI name','text',false,edit?selectedKpi?.name:undefined),options('metric','المؤشر','Metric',metrics,false,edit?selectedKpi?.metric:undefined),f('target','المستهدف','Target','number',false,edit?selectedKpi?.target:undefined),options('period','الفترة','Period',periods,false,edit?selectedKpi?.period:undefined),f('period_start','بداية الفترة','Start','date',false,edit?selectedKpi?.period_start:undefined),f('period_end','نهاية الفترة','End','date',false,edit?selectedKpi?.period_end:undefined),f('weight','الوزن (اختياري)','Weight (optional)','number',true,edit?selectedKpi?.weight:undefined)];
 return <div className="space-y-5">
  <p className="portal-card">{t('إدارة الحسابات وروابط المالك والمستأجر والوسيط متاحة في المستخدمين والصلاحيات.','Manage accounts and owner/tenant/broker assignments in Users & Access.')} <a className="underline" href="/users-access">{t('فتح التعيينات','Open assignments')}</a></p>
  <label>{t('العقد لتحديد الوحدة','Contract for unit assignment')}<select className="portal-input" value={contract} onChange={e=>setContract(e.target.value)}><option value="">{t('اختر العقد','Select contract')}</option>{contracts.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label>
  {contract&&<WorkflowForm key={contract} en={en} title={t('تفاصيل الوحدة وخصوصية المالك','Unit details & owner privacy')} operation="CONTRACT_UNIT" fixed={{contract_id:contract}} save={save} fields={[f('unit_label','رقم / اسم الوحدة','Unit label','text',false,data.contracts.find(c=>c.id===contract)?.unit_label),f('unit_details','تفاصيل الوحدة','Unit details','textarea',true,data.contracts.find(c=>c.id===contract)?.unit_details),f('owner_contact_visible','السماح للمالك بعرض اتصال المستأجر','Allow owner to view tenant contact details','checkbox',false,data.contracts.find(c=>c.id===contract)?.owner_contact_visible)]}/>}
  <WorkflowForm en={en} title={t('إضافة مستحق أو فاتورة','Add due or bill')} operation="DUE_SAVE" save={save} fields={[options('contract_id','العقد','Contract',contracts),options('kind','النوع','Kind',[{value:'utility',label:t('مرافق','Utilities')},{value:'service',label:t('خدمات','Services')}]),f('description','الوصف','Description'),f('amount','المبلغ','Amount','number'),f('due_date','تاريخ الاستحقاق','Due date','date'),f('period_start','بداية الفترة','Period start','date'),f('period_end','نهاية الفترة','Period end','date')]}/>
  <div className="portal-card space-y-3"><h3 className="font-bold">{t('ربط إيصال محصل بمستحق','Link collected receipt to a due')}</h3><select className="portal-input" value={payment} onChange={e=>{setPayment(e.target.value);setDue('');}}><option value="">{t('اختر الإيصال','Select receipt')}</option>{data.payments.filter(p=>p.flow==='INCOME').map(p=><option value={p.id} key={p.id}>{p.date} · {money(p.amount)} · {data.contracts.find(c=>c.id===p.contract_id)?.number}</option>)}</select><select className="portal-input" value={due} onChange={e=>setDue(e.target.value)}><option value="">{t('اختر المستحق','Select due')}</option>{data.dues.filter(d=>d.contract_id===data.payments.find(p=>p.id===payment)?.contract_id).map(d=><option key={d.id} value={d.id}>{d.description} · {d.due_date}</option>)}</select><button className="portal-button" disabled={!payment||!due} onClick={()=>void save({operation:'PAYMENT_LINK',payment_id:payment,due_id:due})}>{t('ربط','Link')}</button></div>
  <div className="portal-card"><h3 className="font-bold">{t('رسوم ومصروفات تحمل على المالك','Fees & expenses charged to owners')}</h3>{data.payments.filter(p=>p.category!=='RENTAL_PAYMENT').map(p=><label className="block mt-3" key={p.id}><input type="checkbox" checked={p.owner_charge} onChange={e=>void save({operation:'OWNER_CHARGE',payment_id:p.id,owner_charge:e.target.checked})}/> {p.date} · {p.category} · {money(p.amount)}</label>)}</div>
  <WorkflowForm en={en} title={t('إضافة هدف للوسيط','Assign broker KPI')} operation="KPI_SAVE" save={save} fields={kpiFields()}/>
  <label>{t('تعديل هدف قائم','Edit existing KPI')}<select className="portal-input" value={kpi} onChange={e=>setKpi(e.target.value)}><option value="">{t('اختر الهدف','Select KPI')}</option>{data.kpis.map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label>
  {selectedKpi&&<WorkflowForm key={kpi} en={en} title={t('تعديل الهدف','Edit KPI')} operation="KPI_SAVE" fixed={{id:kpi,broker_user_id:selectedKpi.broker_user_id}} save={save} fields={kpiFields(true)}/>}
  <WorkflowForm en={en} title={t('تسجيل واقعة لمؤشر مخصص','Record custom KPI event')} operation="KPI_EVENT" save={save} fields={[options('kpi_id','الهدف المخصص','Custom KPI',data.kpis.filter(k=>k.metric==='custom').map(k=>({value:k.id,label:k.name}))),f('value','القيمة','Value','number'),f('date','تاريخ الواقعة','Event date','date'),f('note','وصف الواقعة','Event description','textarea')]}/>
 </div>;
}
