'use client';
import type { PortalDashboard, Maintenance } from '@/lib/portal/workflows';
import WorkflowForm from './WorkflowForm';
import Badge,{statusNames} from './StatusBadge';
const transitions:Record<string,string[]>={pending:['under_review'],under_review:['awaiting_customer_approval','awaiting_manager_approval','rejected'],awaiting_manager_approval:['scheduled','rejected'],scheduled:['in_progress'],in_progress:['completed'],completed:['closed']};
export default function MaintenancePanel({data,en,executive,userId,historyOnly,busy,save,photo,attachment,money}:{data:PortalDashboard;en:boolean;executive:boolean;userId:string;historyOnly:boolean;busy:boolean;save:(body:unknown)=>Promise<boolean>;photo:(task:Maintenance,file:File)=>Promise<void>;attachment:(task:Maintenance,id:string)=>Promise<void>;money:(n:number)=>string}){
 const t=(ar:string,english:string)=>en?english:ar;
 return <div className="space-y-5">
  {!historyOnly&&<WorkflowForm en={en} title={t('طلب صيانة جديد','New maintenance request')} operation="MAINTENANCE_CREATE" save={save} fields={[{name:'property_id',label:t('العقار','Property'),options:data.properties.map(p=>({value:p.id,label:p.name}))},{name:'contract_id',label:t('العقد / الوحدة','Contract / unit'),options:data.contracts.map(c=>({value:c.id,label:`${c.number} — ${c.unit_label||t('الوحدة غير محددة','Unit not set')}`})),optional:data.role!=='TENANT'},...(data.role==='TENANT'?[]:[{name:'unit_label',label:t('الوحدة','Unit'),optional:true}]),{name:'category',label:t('نوع الصيانة','Category')},{name:'description',label:t('وصف المشكلة','Description'),type:'textarea'},{name:'preferred_visit_at',label:t('موعد الزيارة المفضل','Preferred visit'),type:'datetime-local',optional:true}]}/>}
  {data.maintenance.map(task=><section className="portal-card space-y-3" key={task.id}>
   <div className="flex gap-3 flex-wrap items-center"><h3 className="font-bold text-lg flex-1">{data.properties.find(p=>p.id===task.property_id)?.name} · {task.unit_label} · {task.category}</h3><Badge en={en} status={task.status}/></div><p>{task.description}</p><p>{t('التكلفة','Cost')}: {money(task.cost)} · {t('يتحملها','Paid by')}: {task.cost_bearer==='owner'?t('المالك','Owner'):task.cost_bearer==='tenant'?t('المستأجر','Tenant'):t('الشركة','Company')}</p>{task.scheduled_at&&<p>{t('موعد التنفيذ','Visit time')}: {new Date(task.scheduled_at).toLocaleString(en?'en-SA':'ar-SA')}</p>}
   <details><summary className="font-bold cursor-pointer">{t('سجل الحالة وملف الوحدة','Status history & unit profile')}</summary><ol className="space-y-3 mt-3">{task.history.map((h,i)=><li key={i} className="border-s-2 border-[#BFD9C6] ps-3"><Badge en={en} status={h.to}/> {new Date(h.date).toLocaleString(en?'en-SA':'ar-SA')} · {h.actor_name}<p>{h.note}</p></li>)}</ol><h4 className="font-bold mt-4">{t('تاريخ صيانة الوحدة','Unit maintenance history')}</h4>{data.maintenance.filter(m=>m.property_id===task.property_id&&m.unit_label===task.unit_label).map(m=><p className="mt-2" key={m.id}>{m.category} · {money(m.cost)} · <Badge en={en} status={m.status}/></p>)}</details>
   <div className="flex gap-3 flex-wrap">{task.attachments.map(a=><button className="underline" key={a.id} onClick={()=>void attachment(task,a.id)}>{a.filename}</button>)}</div>
   {!historyOnly&&<label>{t('إرفاق صورة (حتى 5 ميجابايت)','Attach photo (up to 5 MB)')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void photo(task,f);e.target.value='';}}/></label>}
   {!historyOnly&&task.status==='pending'&&task.requested_by===userId&&<button disabled={busy} className="rounded border border-red-300 px-3 py-2" onClick={()=>void save({operation:'MAINTENANCE_TRANSITION',task_id:task.id,status:'cancelled',note:t('ألغي بواسطة مقدم الطلب','Cancelled by requester')})}>{t('إلغاء الطلب','Cancel request')}</button>}
   {!historyOnly&&task.status==='awaiting_customer_approval'&&task.cost_customer_id===userId&&<div className="flex gap-3"><button className="portal-button" disabled={busy} onClick={()=>void save({operation:'MAINTENANCE_TRANSITION',task_id:task.id,status:'awaiting_manager_approval',note:t('الموافقة على التكلفة','Cost approved')})}>{t('الموافقة على التكلفة','Approve cost')}</button><button disabled={busy} onClick={()=>void save({operation:'MAINTENANCE_TRANSITION',task_id:task.id,status:'rejected',note:t('رفض التكلفة','Cost rejected')})}>{t('رفض','Reject')}</button></div>}
   {executive&&task.status==='under_review'&&<WorkflowForm en={en} title={t('عرض التكلفة','Cost quote')} operation="MAINTENANCE_QUOTE" fixed={{task_id:task.id}} save={save} fields={[{name:'cost',label:t('التكلفة','Cost'),type:'number',value:task.cost},{name:'cost_bearer',label:t('من يتحمل التكلفة','Cost bearer'),value:task.cost_bearer,options:[{value:'tenant',label:t('المستأجر','Tenant')},{value:'owner',label:t('المالك','Owner')},{value:'company',label:t('الشركة','Company')}]},{name:'cost_customer_id',label:t('العميل المسند لاعتماد التكلفة','Assigned cost approver'),optional:true,value:task.cost_customer_id,options:data.customers.filter(c=>['TENANT','OWNER'].includes(c.role)).map(c=>({value:c.id,label:c.name}))}]}/>}
   {executive&&transitions[task.status]&&<WorkflowForm en={en} title={t('تحديث المرحلة','Next stage')} operation="MAINTENANCE_TRANSITION" fixed={{task_id:task.id}} save={save} fields={[{name:'status',label:t('الحالة التالية','Next status'),options:transitions[task.status].filter(s=>task.status!=='under_review'||(task.cost_bearer==='company'?s!=='awaiting_customer_approval':s!=='awaiting_manager_approval')).map(value=>({value,label:en?value.replaceAll('_',' '):statusNames[value]}))},{name:'note',label:t('ملاحظة','Note'),optional:true},{name:'scheduled_at',label:t('موعد التنفيذ (عند الجدولة)','Visit time (for scheduling)'),type:'datetime-local',optional:true}]}/>}
  </section>)}{!data.maintenance.length&&<p className="portal-card">{t('لا توجد طلبات صيانة.','No maintenance requests.')}</p>}
 </div>;
}
