'use client';
import { useCallback,useEffect,useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabaseClient';
import { portalRequest } from '@/lib/portal/client';
import { ownerEarnings,dueStatus,periodRange } from '@/lib/portal/calculations';
import type { PortalDashboard as Data,Maintenance } from '@/lib/portal/workflows';
import MaintenancePanel from './MaintenancePanel';
import ExecutiveControls from './ExecutiveControls';
import BrokerPanel from './BrokerPanel';
import Badge from './StatusBadge';
import Chart from './PortalChart';
import AuditPanel from './AuditPanel';
export default function PortalDashboard({executive=false}:{executive?:boolean}){
 const auth=useAuth(),[en,setEn]=useState(false),[data,setData]=useState<Data|null>(null),[message,setMessage]=useState(''),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(false);
 const [frequency,setFrequency]=useState<'monthly'|'quarterly'|'yearly'>('monthly'),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const t=(ar:string,english:string)=>en?english:ar,money=(n:number)=>`${Number(n).toLocaleString(en?'en-SA':'ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2})} ${t('ر.س','SAR')}`;
 const load=useCallback(async()=>{try{setData(await portalRequest<Data>('/api/portal/dashboard'));}catch(e){setMessage(e instanceof Error?e.message:'Unable to load');}},[]);
 useEffect(()=>{void load();},[load]);
 const save=async(body:unknown)=>{if(busy)return false;setBusy(true);setMessage('');try{await portalRequest('/api/portal/actions',{method:'POST',body:JSON.stringify(body)});setMessage(t('تم الحفظ','Saved'));await load();return true;}catch(e){setMessage(e instanceof Error?e.message:'Unable to save');return false;}finally{setBusy(false);}};
 const download=async(body:unknown)=>{setBusy(true);try{const{data:session}=await supabase.auth.getSession();const response=await fetch('/api/portal/documents',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session?.access_token}`},body:JSON.stringify(body)});if(!response.ok)throw new Error((await response.json()).error||'Document unavailable');const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download='Kohl-document.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setMessage(e instanceof Error?e.message:'Download failed');}finally{setBusy(false);}};
 const photo=async(task:Maintenance,file:File)=>{setBusy(true);try{const{data:session}=await supabase.auth.getSession();const form=new FormData();form.set('task_id',task.id);form.set('file',file);const response=await fetch('/api/portal/attachments',{method:'POST',headers:{Authorization:`Bearer ${session.session?.access_token}`},body:form});if(!response.ok)throw new Error((await response.json()).error);await load();}catch(e){setMessage(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}};
 const attachment=async(task:Maintenance,id:string)=>{try{const result=await portalRequest<{url:string}>(`/api/portal/attachments?task_id=${task.id}&attachment_id=${id}`);window.open(result.url,'_blank','noopener,noreferrer');}catch(e){setMessage(e instanceof Error?e.message:'Unable to open');}};
 if(executive&&!auth.isExecutive)return<p>{t('هذه الصفحة للإدارة فقط.','Executive access required.')}</p>;
 const range=periodRange(date,frequency),earnings=data?ownerEarnings(data,range.start,range.end):[];
 const tabs=executive?['overview','maintenance','assignments','payments','broker','audit']:data?.role==='BROKER'?['overview','broker']:['overview','payments','maintenance'];
 const labels:Record<string,string>={overview:t('نظرة عامة','Overview'),maintenance:t('الصيانة','Maintenance'),assignments:t('التعيينات والوحدات','Assignments & units'),payments:t('الدفعات والفواتير','Payments & bills'),broker:t('العمولات والأهداف','Commissions & KPIs'),audit:t('سجل التدقيق','Audit log')};
 return <div dir={en?'ltr':'rtl'} className="portal-surface min-h-screen rounded-2xl p-4 sm:p-8"><div className="max-w-6xl mx-auto space-y-5">
  <header className="flex gap-3 items-center flex-wrap"><img src="/kohl-icon.png" width={48} height={48} alt="كحل العقارية"/><div className="flex-1"><h1 className="text-xl sm:text-2xl font-bold">{executive?t('إدارة بوابات العملاء','Customer portal management'):data?.role==='TENANT'?t('بوابة المستأجر','Tenant portal'):data?.role==='OWNER'?t('بوابة المالك','Owner portal'):t('بوابة الوسيط','Broker portal')}</h1><p className="text-[#5d7d64]">{auth.currentUser.name}</p></div><button onClick={()=>setEn(!en)}>{en?'العربية':'English'}</button>{!executive&&<button onClick={()=>void auth.signOut()}>{t('خروج','Sign out')}</button>}</header>
  <nav className="flex gap-2 overflow-x-auto pb-2" aria-label={t('أقسام البوابة','Portal sections')}>{tabs.map(id=><button key={id} className={`whitespace-nowrap rounded-lg px-4 py-2 border border-[#BFD9C6] ${tab===id?'bg-[#2F6D3A] text-white':'bg-white'}`} onClick={()=>setTab(id)}>{labels[id]}</button>)}</nav>
  {message&&<p role="status" className="portal-card">{message}</p>}{!data&&<p>{t('جارٍ تحميل السجلات…','Loading records…')}</p>}{auth.profile?.account.history_only&&<p className="portal-card">{t('انتهى العقد. السجلات متاحة للعرض فقط.','Lease ended. Records are available for reading only.')}</p>}
  {data&&tab==='overview'&&<>
   {(data.role==='OWNER'||executive)&&<><div className="portal-card flex gap-3 flex-wrap items-end"><label>{t('الفترة','Period')}<select className="portal-input" value={frequency} onChange={e=>setFrequency(e.target.value as typeof frequency)}><option value="monthly">{t('شهري','Monthly')}</option><option value="quarterly">{t('ربع سنوي','Quarterly')}</option><option value="yearly">{t('سنوي','Yearly')}</option></select></label><label>{t('تاريخ ضمن الفترة','Date within period')}<input type="date" className="portal-input" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><p>{range.start} — {range.end}</p>{data.role==='OWNER'&&<button className="portal-button" disabled={busy} onClick={()=>void download({kind:'statement',start:range.start,end:range.end})}>{t('تنزيل كشف PDF','Download PDF statement')}</button>}</div><p className="text-sm text-[#5d7d64]">{t('إجمالي العقار بالكامل. تعتمد الأرقام على القيود المحاسبية المرتبطة.','Full property totals based on linked accounting records.')}</p><div className="grid sm:grid-cols-3 gap-3">{(['gross','deductions','net'] as const).map(key=><section key={key} className="portal-card"><h2>{key==='gross'?t('الدخل المحصل','Rent collected'):key==='deductions'?t('الاستقطاعات','Deductions'):t('صافي الأرباح','Net earnings')}</h2><p className="text-2xl font-bold mt-2">{money(earnings.reduce((n,row)=>n+row[key],0))}</p></section>)}</div><div className="portal-card overflow-x-auto"><table className="w-full"><thead><tr>{[t('العقار','Property'),t('المتوقع','Expected'),t('المحصل','Received'),t('الاستقطاعات','Deductions'),t('الصافي','Net')].map(label=><th className="p-2 text-start" key={label}>{label}</th>)}</tr></thead><tbody>{earnings.map(row=><tr className="border-t border-[#BFD9C6]" key={row.property_id}><td className="p-2">{row.name}</td><td>{money(row.expected)}</td><td>{money(row.gross)}</td><td>{money(row.deductions)}</td><td>{money(row.net)}</td></tr>)}</tbody></table></div><Chart label={t('صافي الأرباح حسب العقار','Net earnings by property')} rows={earnings.map(row=>({label:row.name,value:row.net}))}/></>}
   {data.role==='BROKER'&&<BrokerPanel data={data} en={en} executive={false} save={save} money={money}/>}
   {data.properties.map(property=><section className="portal-card" key={property.id}><h2 className="font-bold text-xl">{property.name}</h2><p>{property.city} · {property.address}</p>{data.contracts.filter(c=>c.property_id===property.id).map(c=><div key={c.id} className="border-t border-[#BFD9C6] pt-3 mt-3"><h3 className="font-bold">{c.number} · {c.unit_label||t('بيانات الوحدة قيد الإعداد','Unit details pending')}</h3><p>{c.unit_details}</p><p>{c.start_date} — {c.end_date} · {money(c.annual_rent)} {t('سنوياً','annually')}</p>{c.tenant_name&&<p>{c.tenant_name}{c.tenant_phone&&` · ${c.tenant_phone}`}</p>}</div>)}</section>)}
   {!data.properties.length&&data.role!=='BROKER'&&<p className="portal-card">{t('لا توجد عقارات مسندة.','No assigned properties.')}</p>}
  </>}
  {data&&tab==='payments'&&<><h2 className="text-xl font-bold">{t('المستحقات والفواتير','Dues & bills')}</h2>{data.dues.map(d=>{const status=dueStatus(data,d.id);return<section key={d.id} className="portal-card"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-bold">{d.description} · {data.contracts.find(c=>c.id===d.contract_id)?.number}</h3><Badge en={en} status={status.status}/></div><p>{d.due_date} · {d.period_start} — {d.period_end}</p><p>{t('المستحق','Amount')}: {money(d.amount)} · {t('المحصل','Received')}: {money(status.received)} · {t('المتبقي','Outstanding')}: {money(status.outstanding)}</p></section>;})}{!data.dues.length&&<p className="portal-card">{t('لم تسجل الإدارة جدول المستحقات أو الفواتير بعد.','Management has not recorded a due schedule or bills yet.')}</p>}<h2 className="text-xl font-bold">{t('الدفعات المكتملة','Completed payments')}</h2>{data.payments.map(p=><section key={p.id} className="portal-card"><h3 className="font-bold">{data.contracts.find(c=>c.id===p.contract_id)?.number} · {money(p.amount)}</h3><p>{p.date} · {p.method} · {p.category}</p><p>{p.period_start||t('الفترة غير محددة','Period not recorded')} — {p.period_end}</p>{(data.role==='TENANT'||executive)&&p.flow==='INCOME'&&(p.category==='RENTAL_PAYMENT'||p.due_id)&&<button disabled={busy} className="portal-button mt-3" onClick={()=>void download({kind:'payment',payment_id:p.id})}>{t('إثبات دفع PDF','Payment proof PDF')}</button>}</section>)}</>}
  {data&&tab==='maintenance'&&<MaintenancePanel data={data} en={en} executive={executive} userId={auth.currentUser.id} historyOnly={!!auth.profile?.account.history_only} busy={busy} save={save} photo={photo} attachment={attachment} money={money}/>}
  {data&&executive&&tab==='assignments'&&<ExecutiveControls data={data} en={en} save={save} money={money}/>}
  {data&&tab==='broker'&&<BrokerPanel data={data} en={en} executive={executive} save={save} money={money}/>}
  {data&&executive&&tab==='audit'&&<AuditPanel data={data} en={en} currentId={auth.currentUser.id} currentName={auth.currentUser.name}/>}
 </div></div>;
}
